apiVersion: v1
kind: Pod
metadata:
  name: mypod-multi
spec:
  containers:
  - name: busy
    image: busybox:latest
    env:
    - name: OS
      value: "ubuntu"
    - name: DEBUG
      value: "true"
    command: ["/bin/sh", "-c"]
    args:
      - echo "$(OS), $(DEBUG)";
        echo "do next...";
        hostname;
        date
