apiVersion: v1
kind: Pod
metadata:
  namespace: demo
  name: pod-demo2
  labels:
     app: demo
spec:
  containers:
  - name: demo2
    image: nginx:alpine
    ports:
    - containerPort: 80
    resources:
      limits:
        memory: "600Mi"
        cpu: "0.6"      
      requests:
        memory: "200Mi"
        cpu: "0.3"
